spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
#    url: jdbc:mysql://127.0.0.1:3306/iHangbot
#    username: root
#    password: 1234